#!/bin/sh

DOMA_CFG_FILE="/etc/xen/doma.cfg"

# Memory setup
TOTAL_MEMORY=$(xl info | grep total_memory | sed "s/.*: //")
if [[ "${TOTAL_MEMORY}" == "16384" ]]; then
    sed -i "s/memory = .*/memory = 6144/g" $DOMA_CFG_FILE
fi
